services:
  api-gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
        - ${LOCALAPPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${LOCALAPPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    deploy:
      update_config:
        order: start-first

  categoria-service:
    environment:
        ASPNETCORE_ENVIRONMENT: Production
    volumes:
        - ./src/BackEnd/Services/CategoriaService/appsettings.docker.json:/app/appsettings.json:ro
        - ./src/BackEnd/Services/CategoriaService/appsettings.development.json:/app/appsettings.docker.development.json:ro

  despesa-service:
    environment:
        ASPNETCORE_ENVIRONMENT: Production
    volumes:
        - ./src/BackEnd/Services/DespesaService/appsettings.docker.json:/app/appsettings.json:ro
        - ./src/BackEnd/Services/DespesaService/appsettings.development.json:/app/appsettings.docker.development.json:ro
 
  receita-service:
    environment:
       ASPNETCORE_ENVIRONMENT: Production
    volumes:
       - ./src/BackEnd/Services/ReceitaService/appsettings.docker.json:/app/appsettings.json:ro
       - ./src/BackEnd/Services/ReceitaService/appsettings.development.json:/app/appsettings.docker.development.json:ro