services:
  app-angular-dev:
    container_name: dev
    image: alexfariakof/despesas-frontend-angular-dev-img
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4202:80
      - 9230:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certificate/ssl_certificate.pem:/etc/nginx/certificate/ssl_certificate.pem:ro
      - ./certificate/ssl_certificate.key:/etc/nginx/certificate/ssl_certificate.key:ro
    deploy:
      resources:
        limits:
          memory: 500M 
        reservations:
          memory: 256M
